baseurl: https://example.com/
title: Bootstrap demo
languageCode: en-us
defaultContentLanguage: en
paginate: 3
paginatePath: page
theme: hugo-bootstrap-5
taxonomies:
  category: categories
  tag: tags
languages:
  de:
    languageName: Deutsch
    menu:
      main:
        - name: Start
          url: /de/
          weight: 1
        - name: Über uns
          url: /about/
          weight: 2
        - name: Kontakt
          url: /contact/
          weight: 3
  en:
    languageName: English
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: About
          url: /about/
          weight: 2
        - name: Contact
          url: /contact/
          weight: 3
  es:
    languageName: Español
    menu:
      main:
        - name: Casa
          url: /es/
          weight: 1
        - name: Acerca de
          url: /about/
          weight: 2
        - name: Contacto
          url: /contact/
          weight: 3
permalinks:
  post: /:year/:month/:title/
params:
  author: John Doe
  footer: {}
  header: {}
  mainSections: post
  sidebar: {}
